disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace

opt_in_rules: # some rules are only opt-in
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - discarded_notification_center_observer
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - weak_delegate
  - yoda_condition

  # Require team discussion:
#  - explicit_self
#  - implicitly_unwrapped_optional
#  - indentation_width
#  - vertical_whitespace_opening_braces
  
included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# configurable rules can be customized from this configuration file
line_length: 150

weak_delegate: error

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - K
  
identifier_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - x
    - y

reporter: "xcode"
